<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>mdb</AssemblyName>
    <RootNamespace>MaidouBao.Launcher</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MaidouBao.Core\MaidouBao.Core.csproj" />
    <ProjectReference Include="..\MaidouBao.Plugin\MaidouBao.Plugin.csproj" />
  </ItemGroup>
</Project>
