<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Leadscrew</RootNamespace>
    <AssemblyName>Leadscrew</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <AssemblyTitle>丝杠设计</AssemblyTitle>
    <Description>丝杠设计模块 - 梯形螺纹、锯齿形螺纹、滚珠丝杠设计计算</Description>
    <Product>麦豆宝</Product>
    <Copyright>Copyright 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

</Project>
