<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SectionProfileTool</RootNamespace>
    <AssemblyName>SectionProfileTool</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <AssemblyTitle>型材工具</AssemblyTitle>
    <Description>国标型材智能选型与受力仿真分析模块</Description>
    <Product>麦豆宝</Product>
    <Copyright>Copyright 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Plugin.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
