<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>GeoTolerance</RootNamespace>
    <AssemblyName>GeoTolerance</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <AssemblyTitle>形位公差查询</AssemblyTitle>
    <Description>形位公差查询模块 - GB/T 1182标准形位公差等级查询</Description>
    <Product>麦豆宝</Product>
    <Copyright>Copyright 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="images\zxd.bmp">
      <LogicalName>GeoTolerance.zxd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\pmd.bmp">
      <LogicalName>GeoTolerance.pmd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\yd.bmp">
      <LogicalName>GeoTolerance.yd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\yzd.bmp">
      <LogicalName>GeoTolerance.yzd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\pxd.bmp">
      <LogicalName>GeoTolerance.pxd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\czd.bmp">
      <LogicalName>GeoTolerance.czd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\qxd.bmp">
      <LogicalName>GeoTolerance.qxd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\tzd.bmp">
      <LogicalName>GeoTolerance.tzd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\dcd.bmp">
      <LogicalName>GeoTolerance.dcd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\ytd.bmp">
      <LogicalName>GeoTolerance.ytd</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="images\qtd.bmp">
      <LogicalName>GeoTolerance.qtd</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
