<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SpringDesign</RootNamespace>
    <AssemblyName>SpringDesign</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>弹簧设计</AssemblyTitle>
    <Description>迈迪弹簧设计系统 - 圆柱螺旋压缩、拉伸、扭转弹簧设计计算</Description>
    <Product>麦豆宝</Product>
    <Copyright>Copyright 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

</Project>
